name: Release - New Version

on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*
      - release/v*/v*

jobs:
  release:
    uses: kungfu-systems/workflows/.github/workflows/.release-new-version.yml@ci/release-token-scope
    with:
      publish-aws-ci: false
      publish-aws-user: false
      action-bump-version-ref: ci/token-scope-default-branch
