name: Release - New Version

on:
  pull_request:
    types: [closed]
    branches:
      - alpha/v*/v*
      - release/v*/v*

jobs:
  release:
    uses: kungfu-systems/workflows/.github/workflows/.release-new-version.yml@dev/v1/v1.2
    with:
      publish-aws-ci: false
      publish-aws-user: false
      action-bump-version-ref: dev/v3/v3.1
